### PR TITLE
Enables Philippines

### LINKED ISSUE #219: Expand "Ça reste ouvert" data to Philippines
Please check the following requirements:
- [x] You are a team of at least 2 people experienced with OpenStreetMap
- [x] Translate the app via transifex with your country languages. [Filpino already merged](https://github.com/osmontrouge/caresteouvert/pull/145)
- [x] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...)
- [x] Start gathering data about shop open or closed nation wide in https://github.com/PanierAvide/Covid_enseignes/
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

Others questions:

- if you want a localized domain name, please tell us which one
- Each lockdown is different, what shops are open or closed in your country? What should be done in the category list?
  - [x] **Compiled category list from our initial [idea pad](https://hackmd.io/mbQ7Im8XRH-sFHfZT5jUoQ)**: 
[caresteouvert-ph.csv.txt](https://github.com/osmontrouge/caresteouvert/files/4443078/caresteouvert-ph.csv.txt)

## Team
- `GOwin`
- `DearPaul24`
- `Mapbeks`

### PR DESCRIPTION
**Pull request by caugner**
Fix #219.

### CODE REVIEW

**Comment by PanierAvide** [comment]
We don't have any rules in covid_enseignes, while it seems that they are quite common brands in there : https://taginfo.geofabrik.de/asia/philippines/keys/brand#values

So should we wait a bit before enabling Philippines in order to let them complete covid_enseignes ?

**Comment by caugner** [comment]
I think it makes sense to enable them asap so that they can easier showcase it in their community. Not having rules shouldn't block this in my opinion.

Having the map enabled also makes it easier to spot unwanted categories.

**Comment by PanierAvide** [comment]
OK to make this non-blocking, but it may be started ASAP to have a bit of information already showing up (makes a more convincing showcase)

**Comment by caugner** [comment]
I'm not sure about the status of #219, so I'm closing this PR for now (it has conflicts anyway).

**Pull request closed without merging**
