### PR TITLE
[RFC] Add italian rules NO MERGE

### PR DESCRIPTION
**Pull request by fansanelli**
Hello,

in order to address this ticket: #311.
I'd like collect some feedback about these changes.
I'm not completely sure about:

shop=mall
shop=general
craft=hvac
office=delivery

that I would add in a next commit.
I took the freedom to add electrical shops in Hardware (I think usually are a subset of doityourself) and appliance (usually a smaller electronics shop)
Please let me know what you think and what are the next steps to do.

Thanks
Francesco

### CODE REVIEW

**Comment by PanierAvide** [comment]
Helloo, thanks for this PR. No problem with suggested changes in existing categories. By looking at SVG code of new icons, I see that there is a lot of `<g>` markup which seem empty. Please make sure the icons are clean, and also of 18x18px size.

**Comment by PanierAvide** [comment]
Let me know when you think it is stable enough on your side.

**Comment by fansanelli** [comment]
For me this could go ahead. Can you give it a try?

**Comment by PanierAvide** [comment]
Merged, just had to do some fixes on icons (X/Y scale should be 1, and there was still empty lines). So POIs in Italy will show up in around ~1h.

**Pull request merged**
