### PR TITLE
Add Dockerfile and Docker Compose config

### PR DESCRIPTION
**Pull request by caugner**
As an alternative to `./script/server`.

### CODE REVIEW

**Comment by PanierAvide** [comment]
Thanks for offering this PR, can you also update accordingly the README ?

@francois2metz do we rely on `./script/server` in current deployment ? Should we drop it to directly use the Dockerfile provided ?

**Comment by caugner** [comment]
Will do!

Note that I included the db container, although I'm not sure it doesn't anything, because that Dockerfile doesn't have a CMD or ENTRYPOINT.

Also, I'm not what the equivalent of script/test would be.

**Comment by francois2metz** [comment]
> @francois2metz do we rely on ./script/server in current deployment ? Should we drop it to directly use the Dockerfile provided ?

The proposed config it not really useful for development (and `./script/server` is only for development) as the the code is not shared between the host and the container.

> Note that I included the db container, although I'm not sure it doesn't anything, because that Dockerfile doesn't have a CMD or ENTRYPOINT.

Yup it doesn't do anything right now.

**Comment by caugner** [comment]
The `script/server` script doesn't work on Windows, but you're right that this Docker config is useless für development, as it doesn't mount the code as a volume. Closing my PR therefore.

**Pull request closed without merging**
