### PR TITLE
Adds Germany as category area

### LINKED ISSUE #152: Define open place types per country
**Is your feature request related to a problem? Please describe.**

This is about defining what types of places (e.g. `shop=supermarket`) are allowed to be opened where.

So far, this information seems to be specific to France. Now, we're gathering data about Spain (#94) and Germany (#149).

**Describe the solution you'd like**
It would be great to have a common format to describe what types places are allowed to open in whatc country. Possible formats could be JSON or CSV.

**Describe alternatives you've considered**
Alternatively, we could come up with a common format later.

**Additional context**
* https://github.com/osmontrouge/caresteouvert/issues/94#issuecomment-607418246
* https://github.com/osmontrouge/caresteouvert/issues/149

### PR DESCRIPTION
**Pull request by caugner**
Fixes #152.

### CODE REVIEW

**Comment by francois2metz** [comment]
On hold. We are working to load the planet right now.

**Comment by francois2metz** [comment]
@caugner We are almost there. Could you rebase this branch please?

**Comment by caugner** [comment]
Here we go. I would suggest a squash-merge to avoid the noise.

**Comment by caugner** [comment]
@francois2metz Ready to (squash-)merge from my side.

**Pull request merged**
