### PR TITLE
Resize icons

### PR DESCRIPTION
**Pull request by Beck-berry**
Hi there!

Using your data in our application showed me some problems with the icons sizes (some were smaller than the others), which I tried to fix. Please check these modifications whether they are ok for you too!

### CODE REVIEW

**Comment by francois2metz** [comment]
Hi! Can you include a screenshot before and after the changes ?

**Comment by Beck-berry** [comment]
On the map they look the same, but they got bigger in the upper left corner when a location is opened. However their coloring has some trouble (which I did not notice at first):

Before this commit:
Screenshot_2020-05-08_13-53-30
Screenshot_2020-05-08_13-53-44

After this commit:
Screenshot_2020-05-08_13-55-26
Screenshot_2020-05-08_13-55-11

I'm a bit unsure where does that white box comes from since none of the others has the same issue. Did you know about this already?

**Comment by francois2metz** [comment]
Yup there is a default rectangle in the SVG. Let me fix that for you.

**Comment by francois2metz** [comment]
I believe this should be fixed in a few minutes once the fix is live. Tell me if it's works for you.

**Comment by Beck-berry** [comment]
Looks better, thank you!

**Pull request closed without merging**
