### PR TITLE
Adds icecream to categories

### LINKED ISSUE #174: Show places selling ice cream
**Is your feature request related to a problem? Please describe.**
* Shops selling ice cream ([`shop=ice_cream`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dice_cream), e.g. Amorino) are apparently allowed to open for takeway.
* However, they are not shown on the map yet.

**Describe the solution you'd like**
Show `shop=ice_cream` as part of the "Shops" category.

**Describe alternatives you've considered**
Alternatively, it would suffice to show those with `takeaway=true`.

**Additional context**
(None for now.)

### PR DESCRIPTION
**Pull request by caugner**
Fixes #174.

### CODE REVIEW

**Comment by caugner** [comment]
Changed `icecream` to `ice_cream` to be consistent with OSM.

**Comment by PanierAvide** [comment]
Are ice cream shops really open during lockdown ?

**Comment by caugner** [comment]
I have seen an Amorino ice cream shop that was open and serving customers with my own eyes, so I guess yes. Possibly qualifies as "restauration à emporter".

**Comment by PanierAvide** [comment]
OK, so would you mind also add icon + mapicon for these ? Like this one https://github.com/gravitystorm/openstreetmap-carto/blob/9fb827629b468b1ceb6e196f41822d2cace357af/symbols/amenity/ice_cream.svg

Note that SVG in our repo should be 18px x 18px

**Comment by PanierAvide** [comment]
As I'm integrating restaurant & co, don't do the icon work, I will do it in the same time ;-)

**Comment by PanierAvide** [comment]
Done by 2bdc4ab, closing this PR.

**Pull request closed without merging**
