### PR TITLE
Italian logo and OG

### PR DESCRIPTION
**Pull request by naposm**
Hi! It's me again. I've added the Italian logos and OGs. Let me know if there's something wrong 😄 

EDIT: Again, you can ignore the other files, I'm still learning to use GitHub 🤦‍♂️ 

EDIT 2: I've also updated the Italian article for townhalls with the new custom url

### CODE REVIEW

**Comment by PanierAvide** [comment]
Thanks for the PR. Note that we are changing our logo (#736), and also we have a graphic designer in team who can take care of this. Can you give me your email so I can invite you in our Mattermost ? That way, you will be able to discuss with him and he will send you updated logo.

**Comment by naposm** [comment]
Sure! My emai is naposm-talkit@outlook.it
I'm also available for videos, banners and other media translations 😄

**Comment by naposm** [comment]
So will the old logo be merged until the new logo comes out?

**Comment by naposm** [comment]
The new logo is very nice, I like it!

**Comment by naposm** [comment]
I've added the new logo! 😃

**Comment by PanierAvide** [comment]
As I updated all logos, you might need to merge master branch in your current work branch, and update blog articles accordingly.

**Comment by naposm** [comment]
Done in #746 😄

**Pull request closed without merging**
