### PR TITLE
Add shop categories and update icons

### PR DESCRIPTION
**Pull request by caugner**

### CODE REVIEW

**Comment by PanierAvide** [comment]
Thanks for this PR. Can you move `shop=frame` in the `home_equipment` category ? Because shop category is quite full already, so if we can move some shops which fit more or less elsewhere, that would be better :wink: 

By the way, for icons, for some reason the sprite generator is buggy if SVG icons has `<g>` markup with `tranform` properties or so. On previous icon set I had to edit manually to remove this kind of markup (only keep path markup), then edit back in Inkscape to move/scale at right place. Can you try to do this clean-up on given icons ? If it's too annoying let me know, I will take care of it.

**Comment by caugner** [comment]
> Thanks for this PR. Can you move `shop=frame` in the `home_equipment` category ? Because shop category is quite full already, so if we can move some shops which fit more or less elsewhere, that would be better wink

Fixed in fa16627.

> By the way, for icons, for some reason the sprite generator is buggy if SVG icons has `<g>` markup with `tranform` properties or so. On previous icon set I had to edit manually to remove this kind of markup (only keep path markup), then edit back in Inkscape to move/scale at right place. Can you try to do this clean-up on given icons ? If it's too annoying let me know, I will take care of it.

I'm not sure how to do this. Does this affect all icons or only those from @CarstenWeithoener?

**Comment by PanierAvide** [comment]
I'm not sure, but usually icons from osm-carto are giving less trouble than from other sources : https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop

**Comment by CarstenWeithoener** [comment]
@PanierAvide @caugner I examined the svg files I contributed. The `<g>` tag indicates a group. 

I compared my svg files with an icon from [osm-carto](https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop) in a Text Editor. I saw that all apps I use (Inkscape, Affinty Designer, Adobe Illustrator) are leaving their own traces in the code.  

So I cleaned them a bit. Here is the archive: [shop_SVGs-5.zip](https://github.com/osmontrouge/caresteouvert/files/4614838/shop_SVGs-5.zip)

- second_hand-2.svg
- department_store-3.svg
- health_food-3.svg
- art-3.svg
- lottery-2.svg
- mall-3.svg

I hope this helps.

**Comment by francois2metz** [comment]
Closing as we close Ça reste ouvert soon #823

**Pull request closed without merging**
